### ISSUE TITLE
Question about Reconstruction dataset visualization

### ISSUE THREAD

**Issue by DavidXu-JJ** [AutodeskAILab/Fusion360GalleryDataset#101]
Hi everyone,
Thanks for your dataset contribution to the community. This is a good dataset, and I like it!
I have some questions about the visualization problem for the Reconstruction dataset.
I wish to get some visualization results for the Brep representation, like the image below.
![image](https://github.com/AutodeskAILab/Fusion360GalleryDataset/assets/68705456/7344793f-9112-430e-aa31-83d3634f448e)

I see there is a solution for Segmentation dataset in https://github.com/AutodeskAILab/Fusion360GalleryDataset/issues/76#issuecomment-822372435

I tried this script, and the result doesn't seem to be similar to the image in the original Reconstruction dataset.
By the way, this script seems to visualize the mesh instead of the Brep representation.

How can I get a similar visualization result in the original Reconstruction dataset? It's better to have a script solution to capture images for a large number of model files. 

Thanks very much in advance!

**Comment by karldd** [comment]
I think you can write some python code using the Fusion 360 API to import them into Fusion 360 then save a screenshot, something like this: https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/tools/fusion360gym/server/command_export.py#L111

**Comment by DavidXu-JJ** [comment]
I will try it later. Many thanks for your quick reply!
