### ISSUE TITLE
Acquire the spatial geometry data of every extrude step

### ISSUE THREAD

**Issue by Enigma-li** [AutodeskAILab/Fusion360GalleryDataset#62]
Hi,

I am now parsing the JSON file to get the sketch extrusion step data, not the surface or BRep file that already released, but the **spatial profiles** and the corresponding extruded **profiles (offset)**, as shown in the figure below (P and P_off):
  
![image](https://user-images.githubusercontent.com/4813714/99586149-38a95780-29df-11eb-91af-3fc45f1668a4.png)

Now I am seeking help from the python tool `sketch_extrude_importer.py`, and it seems that there are some ways to achieve it, but I still not very clear. Some problems are: 
 1. how to get the correct spatial positions, e.g., some sample points on a circle profile? is there any function, like the evaluator in BRep to get the real geometry?
 2. I found only the functions `reconstruct_sketch_curve` involves the 3D point, is it the only way to acquire the geometry?
 3. Is there a way to extract the profile and offset curves directly from the **extrude feature** object? As my understanding, it should contain the base and offset curves to construct the new object.
 4. Is the extrude direction vector stored in the JSON file, cannot find it

If you could help to propose a clear solution, that would be very nice :)

Thanks very much

**Comment by karldd** [comment]
The way I would tackle this, is to hack the reconverter example to, for every extrude, make a second extrude that is a separate body, and use that to extract the curves you want.

I actually made a quick example of this previously. [Take a look at this code](https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/kddw/extrude-tool-export/tools/reconverter/reconverter.py#L76). And you could change it to something like:

```python
        # Second extrude
        # Create a new body this time
        extrude_data["operation"] = "NewBodyFeatureOperation"
        extrude = self.importer.reconstruct_extrude_feature(
            extrude_data,
            extrude_uuid,
            extrude_index,
            sketch_profiles,
            second_extrude=True
        )

        # This will be P
        for face in extrude.startFaces:
                for edge in face.edges:
                        # Do something with the edge.geometry

        # This will be P_off
        for face in extrude.endFaces:
                for edge in face.edges:
                        # Do something with the edge.geometry
```

Doing it this way will handle all the different variations where P can be offset and by creating (then deleting) a new body you will always get the geometry even when the profile may not exist in the actual design. I'm not sure what it will do for symmetric extrudes, but probably won't be an issue.

1. So if you do as suggested above [BRepEdge.geometry](http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-77de8fdd-18ed-47e7-883f-15b2f2a037ab) is what you want. It will give you the [Curve3D](http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-283c1e3d-2260-4d5b-ae9e-f84b8f6a0ca9) base class which has an evaluator if you want to sample line segments.
2. I think it will be easier to pull the profiles from the extruded geometry here, `reconstruct_sketch_curve()` takes the geometry data from the json and draws it as a sketch.
3. Yeap, this is what I would suggest (see above).
4. The direction is not stored directly as it is simply normal to the sketch plane for a given signed distance defined as:
```python
            "extent_one": {
                "distance": {
                    "type": "ModelParameter",
                    "value": -1.2,
                    "name": "d3",
                    "role": "AlongDistance"
                },
```
So here it is going `-1.2` cm, in the opposite direction to the sketch plane.

**Comment by Enigma-li** [comment]
Thanks very much! The solution via extracting from **extrude** is feasible. Actually, I also need the curves in the side faces, thus I would use `extrude.faces` to extract all the faces and sample the stroke lines from the resulting curves. Some of the models work well in this way, except there are cylinder side faces.

![image](https://user-images.githubusercontent.com/4813714/99601768-fc362580-29f7-11eb-884a-f1d791fdf7db.png)
![image](https://user-images.githubusercontent.com/4813714/99601891-40c1c100-29f8-11eb-9a14-5141373fa746.png)

What I want is to add any two 'paired profile curves' for a cylinder, as shown here:
![image](https://user-images.githubusercontent.com/4813714/99602335-3227d980-29f9-11eb-82b2-e8ffc72f1130.png)

Regarding this problem, I have two following questions:
1. Does the cylinder side face only contain the top and bottom two circles? Is there any way to hack a bit to add the paired lines from the extrude object? 
2. If no to questions 1, is it possible to first get the **trimmed profiles**, then get all the extrude parameters, and execute the extrude out-of-Fusion360, so that all the geometries can be accessed?

Any suggestions for solving this problem?

**Comment by Enigma-li** [comment]
Thanks very very much for your kind suggestions, I would try a bit 👍

**Comment by Enigma-li** [comment]
Hi Karl,

I worked on the suggested solution, and one case (file name in the released dataset is: 21231_eb9826e5_0008.json) I feel confused is as shown below:
![image](https://user-images.githubusercontent.com/4813714/99696395-904ece00-2a86-11eb-8fa4-aae6ff8f7dd5.png)
![image](https://user-images.githubusercontent.com/4813714/99696428-9775dc00-2a86-11eb-9935-0624114db563.png)

In step two, the top two corners are cut, but the **extrude object** only contains **one body** so as to extract one set of feature edges. 

From my understanding, and also the generated PNG files from the `reconverter` in the master branch, there should be two profiles resulting in two new bodies:
![image](https://user-images.githubusercontent.com/4813714/99697000-34387980-2a87-11eb-93ec-6c823fee5ce0.png)

Is there something wrong with this kind of case?

**Comment by Enigma-li** [comment]
Update: There will be one issue when directly writing the newly added body/bodies into .smt or .step file.

The export function will reset the pointer of the current body, so that after executing the extrude operation, if there are two bodies, then you will not get the original second body. Sample code with this issue is shown below:

```       # Second extrude
        # Create a new body this time
        extrude_data["operation"] = "NewBodyFeatureOperation"
        extrude = self.importer.reconstruct_extrude_feature(
            extrude_data,
            extrude_uuid,
            extrude_index,
            sketch_profiles,
            second_extrude=True
        )
        
       # TODO: Support export of multiple bodies
        for bcnt in range(len(extrude.bodies)):
            step_file = f"{self.json_file.stem}_{extrude_index:04}_{bcnt:04}.step"
            step_file_path = self.output_dir / step_file
            exporter.export_step_from_body(step_file_path, extrude.bodies[bcnt])
```
So either directly process the bodies data or add some check to the `exporter`?

**Comment by karldd** [comment]
Yes that sounds right, it looks like we are moving the body (rather than copying it) to a new component as the Fusion API doesn't support direct export of a body as a step/smt.
https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/tools/common/exporter.py#L78

I think what you want to do is try to copy it instead, I haven't tested this:
```python
transform = adsk.core.Matrix3D.create()
# Create a new component and occurrence of it at the root of the design
temp_occ = self.design.rootComponent.occurrences.addNewComponent(transform)
# Copy our body to the component
body.copyToComponent(temp_comp.component)
# Export STEP
step_export_options = self.design.exportManager.createSTEPExportOptions(str(file.resolve()), temp_comp.component)
design.exportManager.execute(step_export_options)
# Delete the temp component
temp_occ.deleteMe()
```

Its a bit long winded I know...

**Comment by Enigma-li** [comment]
That's true! I can directly process the data instead of exporting it, just want to report this in case someone else will encounter this problem later :)

Thanks very much for your kind and timely reply!
