### ISSUE TITLE
Are sketches inherently 2D?

### ISSUE THREAD

**Issue by iftachg** [AutodeskAILab/Fusion360GalleryDataset#64]
I have been working under the assumption that sketches are 2D but it does not seem like that is necessarily the case.
For example, in object `127202_42451722_0000`, Sketch1 You have two circles, `0ba7f88c-e321-11ea-bb0d-54bf646e7e1f` and `0ba90a02-e321-11ea-8bd1-54bf646e7e1f` which have different normals according to their worldGeometry objects ([0, 0, 0] and [-20, 0, 0] respectively).

For reference I extract the normals from the `curve_obj.worldGeometry` object as calculated in the `reconstruct_sketch_curve` method of `sketch_extrude_importer.py`

**Comment by karldd** [comment]
So it is possible in Fusion 360 to create a [3D sketch](https://www.autodesk.com/products/fusion-360/blog/fusion-360-tech-tip-sketching/), but in practice they can't be used with extrude operations so they won't result in solid geometry in the dataset. It might be possible to have a sketch line that isn't used with an extrude operations, but I have yet to see one.

Sketches can be on planes in either the canonical XY, YZ, XZ orientations or on the planar face of an existing B-Rep.

Below are the two curves in question from 127202_42451722_0000. These are both on the same plane. 
![image](https://user-images.githubusercontent.com/619336/100644893-c4c95200-32f0-11eb-8ed9-e903a918e3c0.png)

Can you share how you are getting the normals? The -20,0,0 and 0,0,0 look like the circle center points:
![image](https://user-images.githubusercontent.com/619336/100645733-ed058080-32f1-11eb-981b-79665a11457c.png)

**Comment by iftachg** [comment]
The method [reconstruct_sketch_curve](https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/tools/common/sketch_extrude_importer.py#L486) various methods are used to create `curve_obj` objects, from which I get the normal using:

`curve_obj.worldGeometry.normal`

**Comment by karldd** [comment]
Inspecting `curve_obj.worldGeometry.normal` in the debugger after [line 508](https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/tools/common/sketch_extrude_importer.py#L508), I get the following normal `[0,0,1]` for both circles. This appears correct to me.

![image](https://user-images.githubusercontent.com/619336/100652051-38705c80-32fb-11eb-834f-0dd8b8a7e09e.png)

So I'm not able to reproduce the `-20,0,0` and `0,0,0` values you are seeing. Those do appear to be the circle center points however.

**Comment by iftachg** [comment]
Thank you, it was indeed a problem in my parsing.
