### ISSUE TITLE
Is face based extrusion sufficient to represent all shapes in the dataset?

### ISSUE THREAD

**Issue by Hippogriff** [AutodeskAILab/Fusion360GalleryDataset#67]
In the paper, the proposed network works on faces, where two faces are selected and operation is predicted. It seems to me that shapes with subtraction operation where subtraction creates a cavity throughout the shape, cannot be represented by this strategy. An example posted below encircled in red.
![unnamed](https://user-images.githubusercontent.com/5190226/103553476-7ec95600-4e7b-11eb-888a-897c941914d5.jpg)

Some of these subtraction cases can be represented using add operation using trimmed faces, but I think it is not always possible to represent all shapes in this dataset with this strategy.

**Comment by karldd** [comment]
Yes that is right, the face to face extrusion cannot exactly represent all shapes in the dataset. From 4.2 in the paper:
> Of the design sequences in the reconstruction dataset, 59.2% can be directly converted to a face extrusion sequence. We estimate that approximately 80% of designs in our dataset can be reconstructed by finding alternative construction sequences.

Finding alternate representations that can represent all shapes is an interesting area for future exploration.

**Comment by Hippogriff** [comment]
Thanx for the quick reply.
