### ISSUE TITLE
Query regarding Dataset Label

### ISSUE THREAD

**Issue by abdulwajid725** [AutodeskAILab/Fusion360GalleryDataset#74]
Hi,
Are there any label/class associated with the fusion 360 dataset.?

**Comment by karldd** [comment]
Good question. The answer is yes and no.

The dataset does not contain human annotated labels, such as those found in ModelNet and ShapeNet where each model is manually classified as a _chair_, _bed_, _dresser_ etc. 

The dataset does contain derived labels from the human design sequence. For example, the segmentation dataset contains per face labels for segmentation. 

![Fusion 360 Gallery Segmentation Dataset](https://raw.githubusercontent.com/AutodeskAILab/Fusion360GalleryDataset/master/docs/images/segmentation_example.jpg)

These labels come from the original design files, meaning the labels reflect how the shapes were designed.

You could use the derived labels for tasks such as:
- Classification of construction sequence length
- Segmentation by extrude operation order
- Segmentation by start/side/end face of an extrude operation

**Comment by karldd** [comment]
Closing for now. Feel free to reopen if you have further questions on this topic.

**Comment by abdulwajid725** [comment]
okay, Thanks



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/19/21,
11:49:55 AM
