### ISSUE TITLE
parsing sketch extrude sequences in segmentation data

### ISSUE THREAD

**Issue by samxuxiang** [AutodeskAILab/Fusion360GalleryDataset#75]
Hi, thank you for releasing the segmentation data. However it seems that the timeline json file only contains reference to face uid, which is different from the json file in reconstruction data that also contains the sketch information. I wonder if there is available parsing code for recovering the sketch-extrude sequences as before?

**Comment by karldd** [comment]
The segmentation and reconstruction datasets come from the same source, the Autodesk Online Gallery, but they have separate formats and purposes.

The reconstruction dataset gives you enough information to completely reconstruct a design from the _sketch_ and _extrude_ operations. The segmentation dataset, on the other hand, only gives you per-face metadata about the modeling operations used when it was modeled (extrude, fillet, chamfer, revolve etc).

So unfortunately there isn't any sketch-extrude sequence information for the segmentation dataset. It's aimed at classic segmentation tasks. 

You can take a look here for more details: https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/docs
@JoeLambourne also just posted the paper for the segmentation dataset, which will give you a feel for how to use the data: https://arxiv.org/abs/2104.00706

**Comment by samxuxiang** [comment]
@karldd Thank you for the reply!
