### ISSUE TITLE
How to visualize the Brep data ?

### ISSUE THREAD

**Issue by cuge1995** [AutodeskAILab/Fusion360GalleryDataset#76]

**Comment by karldd** [comment]
Which dataset are you interested in visualizing? Reconstruction or Segmentation?

**Comment by cuge1995** [comment]
> Which dataset are you interested in visualizing? Reconstruction or Segmentation?

The Segmentation

**Comment by JoeLambourne** [comment]
Hi @cuge1995,

Thank you for your interest in the segmentation dataset.   The easiest way to view the segmentation is by visualizing the obj and seg files.  Here is a very simple example using trimesh

```
import argparse
from pathlib import Path
import numpy as np
import trimesh

def view_file(obj_file, seg_file):
    mesh = trimesh.load_mesh(obj_file)

    color_map = np.array([
		[235, 85, 79, 255],  # ExtrudeSide
		[220, 198, 73, 255], # ExtrudeEnd
		[113, 227, 76, 255], # CutSide
		[0, 226, 124, 255],  # CutEnd
		[23, 213, 221, 255], # Fillet
		[92, 99, 222, 255],  # Chamfer
		[176, 57, 223, 255], # RevolveSide
		[238, 61, 178, 255]  # RevolveEnd
    ], dtype=np.uint8)
    tris_to_segments = np.loadtxt(seg_file, dtype=np.uint64)
    facet_colors = color_map[tris_to_segments]

    mesh.visual.face_colors = facet_colors
    mesh.show()

    print("Completed view_segmentation.py")



if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--meshes_folder", type=str, required=True, help="Path segmentation meshes folder")
    parser.add_argument("--file_stem", type=str, required=True, help="The name of the file to view (without extension).")
    args = parser.parse_args()

    meshes_folder = Path(args.meshes_folder)
    obj_file = meshes_folder / (args.file_stem + ".obj")
    seg_file = meshes_folder / (args.file_stem + ".seg")
    view_file(obj_file, seg_file)
```

To view one of the files, for example 52027_790dbc09_10.obj and 52027_790dbc09_10.seg you then run the script like this

```
python visualization/view_segmentation.py /path/to/SegmentationDataset/s1.0.0/meshes 52027_790dbc09_10
```

If you would like to look at the B-Rep data in the smt file format, then the best way to do this right now is using [Fusion 360](https://www.autodesk.com/education/edu-software/overview?sorting=featured&page=1).  It is free for students and academic use.  The [Fusion API](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-9910880d-2299-4947-917a-39b5f030eef4) provides lots of functionality for extracting data from the B-Rep model.   The [B-Rep faces](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-fdf337dd-6cf2-4115-ab30-9ef9fe891853) are returned from the API in the same order as is provided in the `s1.0.0/breps/*.seg` and `s1.0.0/timeline_info/*.json` files.

You may also be interested to know we are working on a whole set of tools using [Open Cascade](https://github.com/tpaviot/pythonocc-core) to allow you to work with B-Rep data in STEP format and visualize results like the face segmentation.  I'm not quite at the stage where I can give you code for this yet, but it is coming soon.

**Comment by karldd** [comment]
The segmentation viewer can now be found here: https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/segmentation_viewer

**Comment by CodingNovice7** [comment]
> Which dataset are you interested in visualizing? Reconstruction or Segmentation?

Hi, is it possible to visualize this B-rep data for the Assembly and Assembly-Joint datasets?

**Comment by karldd** [comment]
There are a number of tools you can use:

- [Visualize the assemblies as meshes along with their assembly graph](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/assembly_graph)
- [Rebuild the assemblies in Fusion 360](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/assembly2cad)
- [Visualize the joints as meshes](https://github.com/AutodeskAILab/JoinABLe/blob/main/notebooks/joint_set_viewer.ipynb)
- [Rebuild the joint data in Fusion 360](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/joint2cad)

**Comment by CodingNovice7** [comment]
> There are a number of tools you can use:
> 
> * [Visualize the assemblies as meshes along with their assembly graph](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/assembly_graph)
> * [Rebuild the assemblies in Fusion 360](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/assembly2cad)
> * [Visualize the joints as meshes](https://github.com/AutodeskAILab/JoinABLe/blob/main/notebooks/joint_set_viewer.ipynb)
> * [Rebuild the joint data in Fusion 360](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/joint2cad)

Thank you for such a timely and accurate response!
