### ISSUE TITLE
Issue with CAD model + its parts

### ISSUE THREAD

**Issue by abdulwajid725** [AutodeskAILab/Fusion360GalleryDataset#83]
Hi,
As per my understanding of the dataset, in the reconstruction folder we have extrude sequences like "20203_7e31e92a_0000_0001" and its final output after several extrude operations -eg- "20203_7e31e92a_0000". But this final output is the part of some CAD model.
Do we have information about (CAD model + All the parts involved in making it + the sequence in which they were joined to make the CAD model)
Thanks

**Comment by karldd** [comment]
Yes your understanding is correct, but we don't currently provide the source CAD models. We also suppress some features (e.g. fillets) so the shapes do change too. Please see Figure 3 of our revised SIGGRAPH paper: https://arxiv.org/abs/2010.02392
