### ISSUE TITLE
Some problems encountered when running assembly2cad

### ISSUE THREAD

**Issue by nylvy** [AutodeskAILab/Fusion360GalleryDataset#94]
Why this file only has no code for the function to run, what parameter should be passed to the context of the run function, I tried to pass a random number and run it. But unfortunately, he has an error, in the following two lines of code：
        temp_brep_mgr = adsk.fusion.TemporaryBRepManager.get()
        breps = temp_brep_mgr.createFromFile(str(smt_file))
This return value is shown below：
temp_brep_mgr ：is_Valid = False
                              objectType = ' '
                 breps :  count = 0
                              is_Valid = False
                              objectType = ' '
Is this a case of not getting the smt file data? I checked the smt_file path and there is no problem.
I hope you can give me a little help when you have the time, thank you very much!

**Comment by nylvy** [comment]
I tried to open this script in Fusion 360 and rebuilt the cad model, but I don't see the dynamic assembly effect in the first drawing of READE, is this correct?

**Comment by karldd** [comment]
I'm going to need some more information here to test this. For example, what file you are trying to run, what the code is, what the error is etc...
