### ISSUE TITLE
About some variables in the part drawing

### ISSUE THREAD

**Issue by CodingNovice7** [AutodeskAILab/Fusion360GalleryDataset#96]
I am sorry to open another issue, because I am trying to parse the B-REP structure of your provided graph file to JSON format, and I found some variables that are not very clear by comparing your part graph in assembly_joint dataset. 

  1. For example, point_on_face_x(y,z), there are so many points on a face, how is this point selected? 
  2. Some faces have both normal and axis and their values are not the same, how are these two geometrically determined?

**Comment by karldd** [comment]
1. Take a look at the [documentation here](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-96c6af33-7a7f-433e-b630-7e264ff59b91): "a sample point guaranteed to lie on the face's surface, within the face's boundaries, and not on a boundary edge". In practice this point is usually at the center of the face, but that doesn't look to be guaranteed.

2. What properties are available depends on the type of surface. The code for [`find_axis_line_from_face(face)`](https://github.com/AutodeskAILab/JoinABLe/blob/5a3b9933e91269d19b6cc733b244a879eb4bfc30/joint/joint_axis.py#L298) shows how the various properties are used to obtain the joint axis. For documentation, take a look at the derived classes under the [`Surface`](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-GUID-598eb817-a481-4dd4-867e-6dda596351e8) class. For example, [`Cylinder`](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-GUID-f2096bd5-e842-4dcc-b9c4-e1c3859c5973).

**Comment by CodingNovice7** [comment]
Sorry, this issue was caused by some operational problems of mine, sorry for opening a useless issue!
